name: Flatpak

on:
  push:
    branches:
      - master
      - branch/*
  pull_request:
    branches:
      - master
      - branch/*

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: freedesktopsdk/flatpak:20.08-x86_64
      options: --privileged --tmpfs /tmp -v /var/tmp -v /root/.local/share/flatpak

    steps:
      - uses: actions/checkout@v2

      - name: Determine flatpak branch
        id: flatpak_branch
        env:
          GITHUB_REF: ${{ github.ref }}
        run: |
          case "$GITHUB_REF" in
            refs/heads/master)
              FLATPAK_BRANCH=stable
            ;;
            refs/heads/beta)
              FLATPAK_BRANCH=beta
            ;;
            refs/heads/branch/*)
              FLATPAK_BRANCH=${GITHUB_REF##*/}
            ;;
            *)
              exit 1
            ;;
          esac
          echo "::set-output name=branch::$FLATPAK_BRANCH"

      - name: Prime cache
        uses: actions/cache@v2
        with:
          path: |
            .flatpak-builder/ccache
          key: flatpak-builder-${{ steps.flatpak_branch.outputs.branch }}-${{ github.run_id }}
          restore-keys: |
            flatpak-builder-${{ steps.flatpak_branch.outputs.branch }}-
            flatpak-builder-

      - name: Build flatpak
        uses: gasinvein/action-flatpak-build@master
        id: build_flatpak
        with:
          kind: app
          id: org.winehq.Wine
          arch: x86_64
          branch: ${{ steps.flatpak_branch.outputs.branch }}

      - name: Publish to OSTree repo
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/branch/')
        uses: vrutkovs/action-flatpak-upload@main
        with:
          build-repo-path: ${{ steps.build_flatpak.outputs.build-repo }}
          url: https://flatpak.russianfedora.online/repo
          name: stable
          token: ${{ secrets.FLATPAK_REPO_TOKEN }}
